# Site settings
title: Ferns
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://howonlee.github.io" # the base hostname & protocol for your site
github_username:  howonlee

# Build settings
markdown: kramdown
